server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name: sherlock-identity
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DRIVER_CLASS_NAME}
  jpa:
    database-platform: ${JPA_DATABASE_PLATFORM}
    hibernate:
      ddl-auto: validate
  flyway:
    url: ${DATABASE_URL}
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    baselineOnMigrate: true

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS}

jwt:
  secret: ${JWT_SECRET}