server:
  port: 8081

spring:
  application:
    name: sherlock-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: sherlock-identity-id
          uri: lb://sherlock-identity
          predicates:
            - Path=/api/v1/account/**, /api/v1/token/**
        - id: first-microservice
          uri: lb://first-microservice
          predicates:
            - Path=/first/**
          filters:
            - CredentialFilter
            - AuthenticationFilter
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS}
  instance:
    hostname: ${EUREKA_HOSTNAME}

management:
  endpoint:
    env:
      post:
        enabled: true